### ISSUE TITLE
Editing theme globals gives invalid data error

### ISSUE THREAD

**Issue by that0n3guy** [lucky-media/landtamic#6]
I've got a fresh install running and when I try to edit the theme globals (any one edited and hit save) it gives me this error: 

![image](https://user-images.githubusercontent.com/113870/154187406-ce2c29c3-21b9-4569-afa8-9d769d71aa41.png)

**Comment by lokmanm** [comment]
Hi @that0n3guy, this happens because in Menu you probably have a set that you have disabled but the field inside is required. This is an issue with Statamic that will be fixed in `3.3` and we will update accordingly. 

To fix this you will need to delete the unused sets under `Links` in menu and it should get rid of the problem.

[Here is the issue in question](https://github.com/statamic/cms/issues/5092).
